//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.225
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.225。
// 
#pragma warning disable 1591

namespace PerfectXML {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SalesRankNPriceSoap", Namespace="http://www.PerfectXML.com/NETWebSvcs/BookService")]
    public partial class SalesRankNPrice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAmazonSalesRankOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAmazonUKSalesRankOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAmazonDESalesRankOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBNSalesRankOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAmazonPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAmazonUKPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAmazonDEPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBNPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAmazonSalesRankNPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAmazonDESalesRankNPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBNSalesRankNPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAmazonAndBNSalesRankOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAmazonAndBNPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SalesRankNPrice() {
            this.Url = "http://www.perfectxml.net/WebServices/SalesRankNPrice/BookService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAmazonSalesRankCompletedEventHandler GetAmazonSalesRankCompleted;
        
        /// <remarks/>
        public event GetAmazonUKSalesRankCompletedEventHandler GetAmazonUKSalesRankCompleted;
        
        /// <remarks/>
        public event GetAmazonDESalesRankCompletedEventHandler GetAmazonDESalesRankCompleted;
        
        /// <remarks/>
        public event GetBNSalesRankCompletedEventHandler GetBNSalesRankCompleted;
        
        /// <remarks/>
        public event GetAmazonPriceCompletedEventHandler GetAmazonPriceCompleted;
        
        /// <remarks/>
        public event GetAmazonUKPriceCompletedEventHandler GetAmazonUKPriceCompleted;
        
        /// <remarks/>
        public event GetAmazonDEPriceCompletedEventHandler GetAmazonDEPriceCompleted;
        
        /// <remarks/>
        public event GetBNPriceCompletedEventHandler GetBNPriceCompleted;
        
        /// <remarks/>
        public event GetAmazonSalesRankNPriceCompletedEventHandler GetAmazonSalesRankNPriceCompleted;
        
        /// <remarks/>
        public event GetAmazonDESalesRankNPriceCompletedEventHandler GetAmazonDESalesRankNPriceCompleted;
        
        /// <remarks/>
        public event GetBNSalesRankNPriceCompletedEventHandler GetBNSalesRankNPriceCompleted;
        
        /// <remarks/>
        public event GetAmazonAndBNSalesRankCompletedEventHandler GetAmazonAndBNSalesRankCompleted;
        
        /// <remarks/>
        public event GetAmazonAndBNPriceCompletedEventHandler GetAmazonAndBNPriceCompleted;
        
        /// <remarks/>
        public event GetAllCompletedEventHandler GetAllCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.PerfectXML.com/NETWebSvcs/BookService/GetAmazonSalesRank", RequestNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", ResponseNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAmazonSalesRank(string ISBN) {
            object[] results = this.Invoke("GetAmazonSalesRank", new object[] {
                        ISBN});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAmazonSalesRank(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAmazonSalesRank", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAmazonSalesRank(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAmazonSalesRankAsync(string ISBN) {
            this.GetAmazonSalesRankAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void GetAmazonSalesRankAsync(string ISBN, object userState) {
            if ((this.GetAmazonSalesRankOperationCompleted == null)) {
                this.GetAmazonSalesRankOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAmazonSalesRankOperationCompleted);
            }
            this.InvokeAsync("GetAmazonSalesRank", new object[] {
                        ISBN}, this.GetAmazonSalesRankOperationCompleted, userState);
        }
        
        private void OnGetAmazonSalesRankOperationCompleted(object arg) {
            if ((this.GetAmazonSalesRankCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAmazonSalesRankCompleted(this, new GetAmazonSalesRankCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.PerfectXML.com/NETWebSvcs/BookService/GetAmazonUKSalesRank", RequestNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", ResponseNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAmazonUKSalesRank(string ISBN) {
            object[] results = this.Invoke("GetAmazonUKSalesRank", new object[] {
                        ISBN});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAmazonUKSalesRank(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAmazonUKSalesRank", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAmazonUKSalesRank(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAmazonUKSalesRankAsync(string ISBN) {
            this.GetAmazonUKSalesRankAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void GetAmazonUKSalesRankAsync(string ISBN, object userState) {
            if ((this.GetAmazonUKSalesRankOperationCompleted == null)) {
                this.GetAmazonUKSalesRankOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAmazonUKSalesRankOperationCompleted);
            }
            this.InvokeAsync("GetAmazonUKSalesRank", new object[] {
                        ISBN}, this.GetAmazonUKSalesRankOperationCompleted, userState);
        }
        
        private void OnGetAmazonUKSalesRankOperationCompleted(object arg) {
            if ((this.GetAmazonUKSalesRankCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAmazonUKSalesRankCompleted(this, new GetAmazonUKSalesRankCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.PerfectXML.com/NETWebSvcs/BookService/GetAmazonDESalesRank", RequestNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", ResponseNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAmazonDESalesRank(string ISBN) {
            object[] results = this.Invoke("GetAmazonDESalesRank", new object[] {
                        ISBN});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAmazonDESalesRank(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAmazonDESalesRank", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAmazonDESalesRank(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAmazonDESalesRankAsync(string ISBN) {
            this.GetAmazonDESalesRankAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void GetAmazonDESalesRankAsync(string ISBN, object userState) {
            if ((this.GetAmazonDESalesRankOperationCompleted == null)) {
                this.GetAmazonDESalesRankOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAmazonDESalesRankOperationCompleted);
            }
            this.InvokeAsync("GetAmazonDESalesRank", new object[] {
                        ISBN}, this.GetAmazonDESalesRankOperationCompleted, userState);
        }
        
        private void OnGetAmazonDESalesRankOperationCompleted(object arg) {
            if ((this.GetAmazonDESalesRankCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAmazonDESalesRankCompleted(this, new GetAmazonDESalesRankCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.PerfectXML.com/NETWebSvcs/BookService/GetBNSalesRank", RequestNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", ResponseNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBNSalesRank(string ISBN) {
            object[] results = this.Invoke("GetBNSalesRank", new object[] {
                        ISBN});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetBNSalesRank(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetBNSalesRank", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetBNSalesRank(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBNSalesRankAsync(string ISBN) {
            this.GetBNSalesRankAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void GetBNSalesRankAsync(string ISBN, object userState) {
            if ((this.GetBNSalesRankOperationCompleted == null)) {
                this.GetBNSalesRankOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBNSalesRankOperationCompleted);
            }
            this.InvokeAsync("GetBNSalesRank", new object[] {
                        ISBN}, this.GetBNSalesRankOperationCompleted, userState);
        }
        
        private void OnGetBNSalesRankOperationCompleted(object arg) {
            if ((this.GetBNSalesRankCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBNSalesRankCompleted(this, new GetBNSalesRankCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.PerfectXML.com/NETWebSvcs/BookService/GetAmazonPrice", RequestNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", ResponseNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAmazonPrice(string ISBN) {
            object[] results = this.Invoke("GetAmazonPrice", new object[] {
                        ISBN});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAmazonPrice(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAmazonPrice", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAmazonPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAmazonPriceAsync(string ISBN) {
            this.GetAmazonPriceAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void GetAmazonPriceAsync(string ISBN, object userState) {
            if ((this.GetAmazonPriceOperationCompleted == null)) {
                this.GetAmazonPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAmazonPriceOperationCompleted);
            }
            this.InvokeAsync("GetAmazonPrice", new object[] {
                        ISBN}, this.GetAmazonPriceOperationCompleted, userState);
        }
        
        private void OnGetAmazonPriceOperationCompleted(object arg) {
            if ((this.GetAmazonPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAmazonPriceCompleted(this, new GetAmazonPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.PerfectXML.com/NETWebSvcs/BookService/GetAmazonUKPrice", RequestNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", ResponseNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAmazonUKPrice(string ISBN) {
            object[] results = this.Invoke("GetAmazonUKPrice", new object[] {
                        ISBN});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAmazonUKPrice(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAmazonUKPrice", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAmazonUKPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAmazonUKPriceAsync(string ISBN) {
            this.GetAmazonUKPriceAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void GetAmazonUKPriceAsync(string ISBN, object userState) {
            if ((this.GetAmazonUKPriceOperationCompleted == null)) {
                this.GetAmazonUKPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAmazonUKPriceOperationCompleted);
            }
            this.InvokeAsync("GetAmazonUKPrice", new object[] {
                        ISBN}, this.GetAmazonUKPriceOperationCompleted, userState);
        }
        
        private void OnGetAmazonUKPriceOperationCompleted(object arg) {
            if ((this.GetAmazonUKPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAmazonUKPriceCompleted(this, new GetAmazonUKPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.PerfectXML.com/NETWebSvcs/BookService/GetAmazonDEPrice", RequestNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", ResponseNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAmazonDEPrice(string ISBN) {
            object[] results = this.Invoke("GetAmazonDEPrice", new object[] {
                        ISBN});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAmazonDEPrice(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAmazonDEPrice", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAmazonDEPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAmazonDEPriceAsync(string ISBN) {
            this.GetAmazonDEPriceAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void GetAmazonDEPriceAsync(string ISBN, object userState) {
            if ((this.GetAmazonDEPriceOperationCompleted == null)) {
                this.GetAmazonDEPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAmazonDEPriceOperationCompleted);
            }
            this.InvokeAsync("GetAmazonDEPrice", new object[] {
                        ISBN}, this.GetAmazonDEPriceOperationCompleted, userState);
        }
        
        private void OnGetAmazonDEPriceOperationCompleted(object arg) {
            if ((this.GetAmazonDEPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAmazonDEPriceCompleted(this, new GetAmazonDEPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.PerfectXML.com/NETWebSvcs/BookService/GetBNPrice", RequestNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", ResponseNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBNPrice(string ISBN) {
            object[] results = this.Invoke("GetBNPrice", new object[] {
                        ISBN});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetBNPrice(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetBNPrice", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetBNPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBNPriceAsync(string ISBN) {
            this.GetBNPriceAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void GetBNPriceAsync(string ISBN, object userState) {
            if ((this.GetBNPriceOperationCompleted == null)) {
                this.GetBNPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBNPriceOperationCompleted);
            }
            this.InvokeAsync("GetBNPrice", new object[] {
                        ISBN}, this.GetBNPriceOperationCompleted, userState);
        }
        
        private void OnGetBNPriceOperationCompleted(object arg) {
            if ((this.GetBNPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBNPriceCompleted(this, new GetBNPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.PerfectXML.com/NETWebSvcs/BookService/GetAmazonSalesRankNPrice", RequestNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", ResponseNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SalesRankNPrice1 GetAmazonSalesRankNPrice(string ISBN) {
            object[] results = this.Invoke("GetAmazonSalesRankNPrice", new object[] {
                        ISBN});
            return ((SalesRankNPrice1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAmazonSalesRankNPrice(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAmazonSalesRankNPrice", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        /// <remarks/>
        public SalesRankNPrice1 EndGetAmazonSalesRankNPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SalesRankNPrice1)(results[0]));
        }
        
        /// <remarks/>
        public void GetAmazonSalesRankNPriceAsync(string ISBN) {
            this.GetAmazonSalesRankNPriceAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void GetAmazonSalesRankNPriceAsync(string ISBN, object userState) {
            if ((this.GetAmazonSalesRankNPriceOperationCompleted == null)) {
                this.GetAmazonSalesRankNPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAmazonSalesRankNPriceOperationCompleted);
            }
            this.InvokeAsync("GetAmazonSalesRankNPrice", new object[] {
                        ISBN}, this.GetAmazonSalesRankNPriceOperationCompleted, userState);
        }
        
        private void OnGetAmazonSalesRankNPriceOperationCompleted(object arg) {
            if ((this.GetAmazonSalesRankNPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAmazonSalesRankNPriceCompleted(this, new GetAmazonSalesRankNPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.PerfectXML.com/NETWebSvcs/BookService/GetAmazonDESalesRankNPrice", RequestNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", ResponseNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SalesRankNPrice1 GetAmazonDESalesRankNPrice(string ISBN) {
            object[] results = this.Invoke("GetAmazonDESalesRankNPrice", new object[] {
                        ISBN});
            return ((SalesRankNPrice1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAmazonDESalesRankNPrice(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAmazonDESalesRankNPrice", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        /// <remarks/>
        public SalesRankNPrice1 EndGetAmazonDESalesRankNPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SalesRankNPrice1)(results[0]));
        }
        
        /// <remarks/>
        public void GetAmazonDESalesRankNPriceAsync(string ISBN) {
            this.GetAmazonDESalesRankNPriceAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void GetAmazonDESalesRankNPriceAsync(string ISBN, object userState) {
            if ((this.GetAmazonDESalesRankNPriceOperationCompleted == null)) {
                this.GetAmazonDESalesRankNPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAmazonDESalesRankNPriceOperationCompleted);
            }
            this.InvokeAsync("GetAmazonDESalesRankNPrice", new object[] {
                        ISBN}, this.GetAmazonDESalesRankNPriceOperationCompleted, userState);
        }
        
        private void OnGetAmazonDESalesRankNPriceOperationCompleted(object arg) {
            if ((this.GetAmazonDESalesRankNPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAmazonDESalesRankNPriceCompleted(this, new GetAmazonDESalesRankNPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.PerfectXML.com/NETWebSvcs/BookService/GetBNSalesRankNPrice", RequestNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", ResponseNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SalesRankNPrice1 GetBNSalesRankNPrice(string ISBN) {
            object[] results = this.Invoke("GetBNSalesRankNPrice", new object[] {
                        ISBN});
            return ((SalesRankNPrice1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetBNSalesRankNPrice(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetBNSalesRankNPrice", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        /// <remarks/>
        public SalesRankNPrice1 EndGetBNSalesRankNPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SalesRankNPrice1)(results[0]));
        }
        
        /// <remarks/>
        public void GetBNSalesRankNPriceAsync(string ISBN) {
            this.GetBNSalesRankNPriceAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void GetBNSalesRankNPriceAsync(string ISBN, object userState) {
            if ((this.GetBNSalesRankNPriceOperationCompleted == null)) {
                this.GetBNSalesRankNPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBNSalesRankNPriceOperationCompleted);
            }
            this.InvokeAsync("GetBNSalesRankNPrice", new object[] {
                        ISBN}, this.GetBNSalesRankNPriceOperationCompleted, userState);
        }
        
        private void OnGetBNSalesRankNPriceOperationCompleted(object arg) {
            if ((this.GetBNSalesRankNPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBNSalesRankNPriceCompleted(this, new GetBNSalesRankNPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.PerfectXML.com/NETWebSvcs/BookService/GetAmazonAndBNSalesRank", RequestNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", ResponseNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SalesRanks GetAmazonAndBNSalesRank(string ISBN) {
            object[] results = this.Invoke("GetAmazonAndBNSalesRank", new object[] {
                        ISBN});
            return ((SalesRanks)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAmazonAndBNSalesRank(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAmazonAndBNSalesRank", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        /// <remarks/>
        public SalesRanks EndGetAmazonAndBNSalesRank(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SalesRanks)(results[0]));
        }
        
        /// <remarks/>
        public void GetAmazonAndBNSalesRankAsync(string ISBN) {
            this.GetAmazonAndBNSalesRankAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void GetAmazonAndBNSalesRankAsync(string ISBN, object userState) {
            if ((this.GetAmazonAndBNSalesRankOperationCompleted == null)) {
                this.GetAmazonAndBNSalesRankOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAmazonAndBNSalesRankOperationCompleted);
            }
            this.InvokeAsync("GetAmazonAndBNSalesRank", new object[] {
                        ISBN}, this.GetAmazonAndBNSalesRankOperationCompleted, userState);
        }
        
        private void OnGetAmazonAndBNSalesRankOperationCompleted(object arg) {
            if ((this.GetAmazonAndBNSalesRankCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAmazonAndBNSalesRankCompleted(this, new GetAmazonAndBNSalesRankCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.PerfectXML.com/NETWebSvcs/BookService/GetAmazonAndBNPrice", RequestNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", ResponseNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Prices GetAmazonAndBNPrice(string ISBN) {
            object[] results = this.Invoke("GetAmazonAndBNPrice", new object[] {
                        ISBN});
            return ((Prices)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAmazonAndBNPrice(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAmazonAndBNPrice", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        /// <remarks/>
        public Prices EndGetAmazonAndBNPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Prices)(results[0]));
        }
        
        /// <remarks/>
        public void GetAmazonAndBNPriceAsync(string ISBN) {
            this.GetAmazonAndBNPriceAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void GetAmazonAndBNPriceAsync(string ISBN, object userState) {
            if ((this.GetAmazonAndBNPriceOperationCompleted == null)) {
                this.GetAmazonAndBNPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAmazonAndBNPriceOperationCompleted);
            }
            this.InvokeAsync("GetAmazonAndBNPrice", new object[] {
                        ISBN}, this.GetAmazonAndBNPriceOperationCompleted, userState);
        }
        
        private void OnGetAmazonAndBNPriceOperationCompleted(object arg) {
            if ((this.GetAmazonAndBNPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAmazonAndBNPriceCompleted(this, new GetAmazonAndBNPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.PerfectXML.com/NETWebSvcs/BookService/GetAll", RequestNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", ResponseNamespace="http://www.PerfectXML.com/NETWebSvcs/BookService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public All GetAll(string ISBN) {
            object[] results = this.Invoke("GetAll", new object[] {
                        ISBN});
            return ((All)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAll(string ISBN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAll", new object[] {
                        ISBN}, callback, asyncState);
        }
        
        /// <remarks/>
        public All EndGetAll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((All)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllAsync(string ISBN) {
            this.GetAllAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void GetAllAsync(string ISBN, object userState) {
            if ((this.GetAllOperationCompleted == null)) {
                this.GetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllOperationCompleted);
            }
            this.InvokeAsync("GetAll", new object[] {
                        ISBN}, this.GetAllOperationCompleted, userState);
        }
        
        private void OnGetAllOperationCompleted(object arg) {
            if ((this.GetAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCompleted(this, new GetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.PerfectXML.com/NETWebSvcs/BookService")]
    public partial class SalesRankNPrice1 {
        
        private string salesRankField;
        
        private string priceField;
        
        /// <remarks/>
        public string SalesRank {
            get {
                return this.salesRankField;
            }
            set {
                this.salesRankField = value;
            }
        }
        
        /// <remarks/>
        public string Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.PerfectXML.com/NETWebSvcs/BookService")]
    public partial class All {
        
        private string amazonSalesRankField;
        
        private string amazonPriceField;
        
        private string bNSalesRankField;
        
        private string bNPriceField;
        
        /// <remarks/>
        public string AmazonSalesRank {
            get {
                return this.amazonSalesRankField;
            }
            set {
                this.amazonSalesRankField = value;
            }
        }
        
        /// <remarks/>
        public string AmazonPrice {
            get {
                return this.amazonPriceField;
            }
            set {
                this.amazonPriceField = value;
            }
        }
        
        /// <remarks/>
        public string BNSalesRank {
            get {
                return this.bNSalesRankField;
            }
            set {
                this.bNSalesRankField = value;
            }
        }
        
        /// <remarks/>
        public string BNPrice {
            get {
                return this.bNPriceField;
            }
            set {
                this.bNPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.PerfectXML.com/NETWebSvcs/BookService")]
    public partial class Prices {
        
        private string amazonPriceField;
        
        private string bNPriceField;
        
        /// <remarks/>
        public string AmazonPrice {
            get {
                return this.amazonPriceField;
            }
            set {
                this.amazonPriceField = value;
            }
        }
        
        /// <remarks/>
        public string BNPrice {
            get {
                return this.bNPriceField;
            }
            set {
                this.bNPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.PerfectXML.com/NETWebSvcs/BookService")]
    public partial class SalesRanks {
        
        private string amazonSalesRankField;
        
        private string bNSalesRankField;
        
        /// <remarks/>
        public string AmazonSalesRank {
            get {
                return this.amazonSalesRankField;
            }
            set {
                this.amazonSalesRankField = value;
            }
        }
        
        /// <remarks/>
        public string BNSalesRank {
            get {
                return this.bNSalesRankField;
            }
            set {
                this.bNSalesRankField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAmazonSalesRankCompletedEventHandler(object sender, GetAmazonSalesRankCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAmazonSalesRankCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAmazonSalesRankCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAmazonUKSalesRankCompletedEventHandler(object sender, GetAmazonUKSalesRankCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAmazonUKSalesRankCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAmazonUKSalesRankCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAmazonDESalesRankCompletedEventHandler(object sender, GetAmazonDESalesRankCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAmazonDESalesRankCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAmazonDESalesRankCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetBNSalesRankCompletedEventHandler(object sender, GetBNSalesRankCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBNSalesRankCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBNSalesRankCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAmazonPriceCompletedEventHandler(object sender, GetAmazonPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAmazonPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAmazonPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAmazonUKPriceCompletedEventHandler(object sender, GetAmazonUKPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAmazonUKPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAmazonUKPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAmazonDEPriceCompletedEventHandler(object sender, GetAmazonDEPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAmazonDEPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAmazonDEPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetBNPriceCompletedEventHandler(object sender, GetBNPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBNPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBNPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAmazonSalesRankNPriceCompletedEventHandler(object sender, GetAmazonSalesRankNPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAmazonSalesRankNPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAmazonSalesRankNPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesRankNPrice1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesRankNPrice1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAmazonDESalesRankNPriceCompletedEventHandler(object sender, GetAmazonDESalesRankNPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAmazonDESalesRankNPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAmazonDESalesRankNPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesRankNPrice1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesRankNPrice1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetBNSalesRankNPriceCompletedEventHandler(object sender, GetBNSalesRankNPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBNSalesRankNPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBNSalesRankNPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesRankNPrice1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesRankNPrice1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAmazonAndBNSalesRankCompletedEventHandler(object sender, GetAmazonAndBNSalesRankCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAmazonAndBNSalesRankCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAmazonAndBNSalesRankCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesRanks Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesRanks)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAmazonAndBNPriceCompletedEventHandler(object sender, GetAmazonAndBNPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAmazonAndBNPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAmazonAndBNPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Prices Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Prices)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllCompletedEventHandler(object sender, GetAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public All Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((All)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591